---- 1. CREACIÓN DEL TABLESPACE
-- tablespace principal
CREATE TABLESPACE TS_GILCAR
DATAFILE 'C:\app\danie\product\21c\oradata\XE\GILCAR02.DBF'
SIZE 100M
AUTOEXTEND ON NEXT 50M
MAXSIZE UNLIMITED;
--.CREAR TABLESPACE TEMPORAL
CREATE TEMPORARY TABLESPACE TS_GILCAR_TEMP
TEMPFILE 'C:\app\danie\product\21c\oradata\XE\GILCARTEMP2.DBF'
SIZE 50M
AUTOEXTEND ON NEXT 25M
MAXSIZE UNLIMITED;


-- 2. Crear usuario para el proyecto
CREATE USER GILCAR_ADMIN IDENTIFIED BY proyecto2026
DEFAULT TABLESPACE TS_GILCAR
TEMPORARY TABLESPACE TS_GILCAR_TEMP
QUOTA UNLIMITED ON TS_GILCAR;



SELECT USER FROM DUAL;
-- 3. PRIVILEGIOS
-- Privilegios básicos
GRANT CREATE SESSION TO GILCAR_ADMIN;
GRANT CREATE TABLE TO GILCAR_ADMIN;
GRANT CREATE VIEW TO GILCAR_ADMIN;
GRANT CREATE SEQUENCE TO GILCAR_ADMIN;
GRANT CREATE PROCEDURE TO GILCAR_ADMIN;
GRANT CREATE TRIGGER TO GILCAR_ADMIN;
GRANT CREATE SYNONYM TO GILCAR_ADMIN;
GRANT UNLIMITED TABLESPACE TO GILCAR_ADMIN;


--Tablas

CREATE TABLE ROLES (
  ID_ROL        NUMBER         NOT NULL,
  NOMBRE        VARCHAR2(50)   NOT NULL,
  DESCRIPCION   VARCHAR2(200),
  CONSTRAINT PK_ROLES PRIMARY KEY (ID_ROL),
  CONSTRAINT UQ_ROLES_NOMBRE UNIQUE (NOMBRE)
);

-- --------------------------------------------------------------

CREATE TABLE USUARIOS (
  ID_USUARIO              NUMBER          NOT NULL,
  NOMBRE                  VARCHAR2(80)    NOT NULL,
  APELLIDOS               VARCHAR2(120)   NOT NULL,
  CORREO                  VARCHAR2(150)   NOT NULL,
  TELEFONO                VARCHAR2(20),
  CONTRASENA_ENCRIPTADA   VARCHAR2(200)   NOT NULL,
  ID_ROL                  NUMBER          NOT NULL,
  FECHA_REGISTRO          DATE            DEFAULT SYSDATE NOT NULL,
  ESTADO_CUENTA           VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
  CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO),
  CONSTRAINT UQ_USUARIOS_CORREO UNIQUE (CORREO),
  CONSTRAINT FK_USUARIOS_ROL FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL),
  CONSTRAINT CK_USUARIOS_ESTADO CHECK (ESTADO_CUENTA IN ('ACTIVO','INACTIVO','BLOQUEADO'))
);

-- --------------------------------------------------------------
-- AGENTES

CREATE TABLE AGENTES (
  ID_AGENTE         NUMBER         NOT NULL,
  ID_USUARIO        NUMBER         NOT NULL,
  ESPECIALIDAD      VARCHAR2(100),
  TELEFONO          VARCHAR2(20),
  HORARIO_ATENCION  VARCHAR2(100),
  CONSTRAINT PK_AGENTES PRIMARY KEY (ID_AGENTE),
  CONSTRAINT UQ_AGENTES_USUARIO UNIQUE (ID_USUARIO),
  CONSTRAINT FK_AGENTES_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- --------------------------------------------------------------

CREATE TABLE VEHICULOS (
  ID_VEHICULO       NUMBER         NOT NULL,
  MARCA             VARCHAR2(60)   NOT NULL,
  MODELO            VARCHAR2(60)   NOT NULL,
  ANO_FABRICACION   NUMBER(4)      NOT NULL,
  TIPO_VEHICULO     VARCHAR2(40)   NOT NULL,
  KILOMETRAJE       NUMBER(10)     DEFAULT 0 NOT NULL,
  TIPO_COMBUSTIBLE  VARCHAR2(30)   NOT NULL,
  PRECIO            NUMBER(12,2)   NOT NULL,
  ESTADO_VEHICULO   VARCHAR2(20)   DEFAULT 'DISPONIBLE' NOT NULL,
  DESCRIPCION       VARCHAR2(1000),

  CONSTRAINT PK_VEHICULOS PRIMARY KEY (ID_VEHICULO),
  CONSTRAINT CK_VEH_ANO CHECK (ANO_FABRICACION >= 1960),
  CONSTRAINT CK_VEH_KM CHECK (KILOMETRAJE >= 0),
  CONSTRAINT CK_VEH_PRECIO CHECK (PRECIO >= 0),
  CONSTRAINT CK_VEH_ESTADO CHECK (
    ESTADO_VEHICULO IN ('DISPONIBLE','VENDIDO','INACTIVO')
  )
);

ALTER TABLE VEHICULOS
ADD COLOR VARCHAR2(30);
-- --------------------------------------------------------------

CREATE TABLE PUBLICACIONES (
  ID_PUBLICACION      NUMBER        NOT NULL,
  ID_VEHICULO         NUMBER        NOT NULL,
  ID_USUARIO_VENDEDOR NUMBER        NOT NULL,
  FECHA_PUBLICACION   DATE          DEFAULT SYSDATE NOT NULL,
  ESTADO_PUBLICACION  VARCHAR2(20)  DEFAULT 'ACTIVA' NOT NULL,
  CONSTRAINT PK_PUBLICACIONES PRIMARY KEY (ID_PUBLICACION),
  CONSTRAINT UQ_PUBLICACIONES_VEHICULO UNIQUE (ID_VEHICULO),
  CONSTRAINT FK_PUB_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULOS(ID_VEHICULO),
  CONSTRAINT FK_PUB_VENDEDOR FOREIGN KEY (ID_USUARIO_VENDEDOR) REFERENCES USUARIOS(ID_USUARIO),
  CONSTRAINT CK_PUB_ESTADO CHECK (ESTADO_PUBLICACION IN ('ACTIVA','PAUSADA','CERRADA'))
);

-- --------------------------------------------------------------

CREATE TABLE SOLICITUDES (
  ID_SOLICITUD      NUMBER        NOT NULL,
  ID_USUARIO        NUMBER        NOT NULL,
  ID_VEHICULO       NUMBER        NOT NULL,
  FECHA_SOLICITUD   DATE          DEFAULT SYSDATE NOT NULL,
  ESTADO_SOLICITUD  VARCHAR2(20)  DEFAULT 'PENDIENTE' NOT NULL,
  MENSAJE           VARCHAR2(1000),
  CONSTRAINT PK_SOLICITUDES PRIMARY KEY (ID_SOLICITUD),
  CONSTRAINT FK_SOL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
  CONSTRAINT FK_SOL_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULOS(ID_VEHICULO),
  CONSTRAINT CK_SOL_ESTADO CHECK (ESTADO_SOLICITUD IN ('PENDIENTE','ATENDIDA','CANCELADA'))
);

-- --------------------------------------------------------------

CREATE TABLE TRANSACCIONES (
  ID_TRANSACCION        NUMBER        NOT NULL,
  ID_PUBLICACION        NUMBER        NOT NULL,
  ID_USUARIO_COMPRADOR  NUMBER        NOT NULL,
  FECHA_TRANSACCION     DATE          DEFAULT SYSDATE NOT NULL,
  MONTO_TOTAL           NUMBER(12,2)  NOT NULL,
  METODO_PAGO           VARCHAR2(30)  NOT NULL,
  ESTADO_TRANSACCION    VARCHAR2(20)  DEFAULT 'EN_PROCESO' NOT NULL,
  CONSTRAINT PK_TRANSACCIONES PRIMARY KEY (ID_TRANSACCION),
  CONSTRAINT FK_TRA_PUBLICACION FOREIGN KEY (ID_PUBLICACION) REFERENCES PUBLICACIONES(ID_PUBLICACION),
  CONSTRAINT FK_TRA_COMPRADOR FOREIGN KEY (ID_USUARIO_COMPRADOR) REFERENCES USUARIOS(ID_USUARIO),
  CONSTRAINT CK_TRA_MONTO CHECK (MONTO_TOTAL >= 0),
  CONSTRAINT CK_TRA_METODO CHECK (METODO_PAGO IN ('EFECTIVO','TRANSFERENCIA','TARJETA','SINPE','OTRO')),
  CONSTRAINT CK_TRA_ESTADO CHECK (ESTADO_TRANSACCION IN ('EN_PROCESO','COMPLETADA','CANCELADA'))
);

-- --------------------------------------------------------------

CREATE TABLE PAGOS (
  ID_PAGO          NUMBER        NOT NULL,
  ID_TRANSACCION   NUMBER        NOT NULL,
  MONTO_PAGADO     NUMBER(12,2)  NOT NULL,
  FECHA_PAGO       DATE          DEFAULT SYSDATE NOT NULL,
  ESTADO_PAGO      VARCHAR2(20)  DEFAULT 'PENDIENTE' NOT NULL,
  CONSTRAINT PK_PAGOS PRIMARY KEY (ID_PAGO),
  CONSTRAINT FK_PAGO_TRANSACCION FOREIGN KEY (ID_TRANSACCION) REFERENCES TRANSACCIONES(ID_TRANSACCION),
  CONSTRAINT CK_PAGO_MONTO CHECK (MONTO_PAGADO >= 0),
  CONSTRAINT CK_PAGO_ESTADO CHECK (ESTADO_PAGO IN ('PENDIENTE','APROBADO','RECHAZADO'))
);

PROMPT === 2) Secuencias ===
CREATE SEQUENCE SEQ_ROLES          START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIOS       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AGENTES        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VEHICULOS      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PUBLICACIONES  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SOLICITUDES    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRANSACCIONES  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAGOS          START WITH 1 INCREMENT BY 1 NOCACHE;

PROMPT === 3) Triggers para IDs automáticos ===
CREATE OR REPLACE TRIGGER TRG_ROLES_BI
BEFORE INSERT ON ROLES
FOR EACH ROW
BEGIN
  IF :NEW.ID_ROL IS NULL THEN :NEW.ID_ROL := SEQ_ROLES.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_USUARIOS_BI
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN :NEW.ID_USUARIO := SEQ_USUARIOS.NEXTVAL; END IF;
  :NEW.FECHA_REGISTRO := NVL(:NEW.FECHA_REGISTRO, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER TRG_AGENTES_BI
BEFORE INSERT ON AGENTES
FOR EACH ROW
BEGIN
  IF :NEW.ID_AGENTE IS NULL THEN :NEW.ID_AGENTE := SEQ_AGENTES.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VEHICULOS_BI
BEFORE INSERT ON VEHICULOS
FOR EACH ROW
BEGIN
  IF :NEW.ID_VEHICULO IS NULL THEN :NEW.ID_VEHICULO := SEQ_VEHICULOS.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PUBLICACIONES_BI
BEFORE INSERT ON PUBLICACIONES
FOR EACH ROW
BEGIN
  IF :NEW.ID_PUBLICACION IS NULL THEN :NEW.ID_PUBLICACION := SEQ_PUBLICACIONES.NEXTVAL; END IF;
  :NEW.FECHA_PUBLICACION := NVL(:NEW.FECHA_PUBLICACION, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER TRG_SOLICITUDES_BI
BEFORE INSERT ON SOLICITUDES
FOR EACH ROW
BEGIN
  IF :NEW.ID_SOLICITUD IS NULL THEN :NEW.ID_SOLICITUD := SEQ_SOLICITUDES.NEXTVAL; END IF;
  :NEW.FECHA_SOLICITUD := NVL(:NEW.FECHA_SOLICITUD, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER TRG_TRANSACCIONES_BI
BEFORE INSERT ON TRANSACCIONES
FOR EACH ROW
BEGIN
  IF :NEW.ID_TRANSACCION IS NULL THEN :NEW.ID_TRANSACCION := SEQ_TRANSACCIONES.NEXTVAL; END IF;
  :NEW.FECHA_TRANSACCION := NVL(:NEW.FECHA_TRANSACCION, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER TRG_PAGOS_BI
BEFORE INSERT ON PAGOS
FOR EACH ROW
BEGIN
  IF :NEW.ID_PAGO IS NULL THEN :NEW.ID_PAGO := SEQ_PAGOS.NEXTVAL; END IF;
  :NEW.FECHA_PAGO := NVL(:NEW.FECHA_PAGO, SYSDATE);
END;
/

---- PKG_VEHICULOS (CRUD + cursores) 

CREATE OR REPLACE PACKAGE PKG_VEHICULOS AS
  PROCEDURE SP_LISTAR(p_out OUT SYS_REFCURSOR);
  PROCEDURE SP_LISTAR_DISPONIBLES(p_out OUT SYS_REFCURSOR);
  PROCEDURE SP_OBTENER_POR_ID(p_id IN NUMBER, p_out OUT SYS_REFCURSOR);

  PROCEDURE SP_INSERTAR(
    p_marca        IN VARCHAR2,
    p_modelo       IN VARCHAR2,
    p_ano          IN NUMBER,
    p_tipo         IN VARCHAR2,
    p_km           IN NUMBER,
    p_combustible  IN VARCHAR2,
    p_precio       IN NUMBER,
    p_color        IN VARCHAR2,
    p_descripcion  IN VARCHAR2,
    p_id_out       OUT NUMBER
  );

  PROCEDURE SP_ACTUALIZAR(
    p_id           IN NUMBER,
    p_marca        IN VARCHAR2,
    p_modelo       IN VARCHAR2,
    p_ano          IN NUMBER,
    p_tipo         IN VARCHAR2,
    p_km           IN NUMBER,
    p_combustible  IN VARCHAR2,
    p_precio       IN NUMBER,
    p_color        IN VARCHAR2,
    p_descripcion  IN VARCHAR2
  );

  PROCEDURE SP_INACTIVAR(p_id IN NUMBER);
END PKG_VEHICULOS;
/


CREATE OR REPLACE PACKAGE BODY PKG_VEHICULOS AS

  PROCEDURE SP_LISTAR(p_out OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_out FOR
      SELECT ID_VEHICULO,
             MARCA,
             MODELO,
             ANO_FABRICACION,
             TIPO_VEHICULO,
             KILOMETRAJE,
             TIPO_COMBUSTIBLE,
             PRECIO,
             NVL(COLOR,'') AS COLOR,
             ESTADO_VEHICULO,
             NVL(DESCRIPCION,'') AS DESCRIPCION
        FROM VEHICULOS
       ORDER BY ID_VEHICULO;
  END;

  PROCEDURE SP_LISTAR_DISPONIBLES(p_out OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_out FOR
      SELECT ID_VEHICULO,
             MARCA,
             MODELO,
             ANO_FABRICACION,
             TIPO_VEHICULO,
             KILOMETRAJE,
             TIPO_COMBUSTIBLE,
             PRECIO,
             NVL(COLOR,'') AS COLOR,
             ESTADO_VEHICULO,
             NVL(DESCRIPCION,'') AS DESCRIPCION
        FROM VEHICULOS
       WHERE ESTADO_VEHICULO = 'DISPONIBLE'
       ORDER BY ID_VEHICULO;
  END;

  PROCEDURE SP_OBTENER_POR_ID(p_id IN NUMBER, p_out OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_out FOR
      SELECT ID_VEHICULO,
             MARCA,
             MODELO,
             ANO_FABRICACION,
             TIPO_VEHICULO,
             KILOMETRAJE,
             TIPO_COMBUSTIBLE,
             PRECIO,
             NVL(COLOR,'') AS COLOR,
             ESTADO_VEHICULO,
             NVL(DESCRIPCION,'') AS DESCRIPCION
        FROM VEHICULOS
       WHERE ID_VEHICULO = p_id;
  END;

  PROCEDURE SP_INSERTAR(
    p_marca        IN VARCHAR2,
    p_modelo       IN VARCHAR2,
    p_ano          IN NUMBER,
    p_tipo         IN VARCHAR2,
    p_km           IN NUMBER,
    p_combustible  IN VARCHAR2,
    p_precio       IN NUMBER,
    p_color        IN VARCHAR2,
    p_descripcion  IN VARCHAR2,
    p_id_out       OUT NUMBER
  ) IS
  BEGIN
    INSERT INTO VEHICULOS(
      ID_VEHICULO, MARCA, MODELO, ANO_FABRICACION, TIPO_VEHICULO,
      KILOMETRAJE, TIPO_COMBUSTIBLE, PRECIO, ESTADO_VEHICULO, COLOR, DESCRIPCION
    ) VALUES (
      NULL,
      TRIM(p_marca),
      TRIM(p_modelo),
      p_ano,
      TRIM(p_tipo),
      NVL(p_km,0),
      TRIM(p_combustible),
      p_precio,
      'DISPONIBLE',
      TRIM(p_color),
      p_descripcion
    )
    RETURNING ID_VEHICULO INTO p_id_out;
  END;

  PROCEDURE SP_ACTUALIZAR(
    p_id           IN NUMBER,
    p_marca        IN VARCHAR2,
    p_modelo       IN VARCHAR2,
    p_ano          IN NUMBER,
    p_tipo         IN VARCHAR2,
    p_km           IN NUMBER,
    p_combustible  IN VARCHAR2,
    p_precio       IN NUMBER,
    p_color        IN VARCHAR2,
    p_descripcion  IN VARCHAR2
  ) IS
  BEGIN
    UPDATE VEHICULOS
       SET MARCA = TRIM(p_marca),
           MODELO = TRIM(p_modelo),
           ANO_FABRICACION = p_ano,
           TIPO_VEHICULO = TRIM(p_tipo),
           KILOMETRAJE = NVL(p_km,0),
           TIPO_COMBUSTIBLE = TRIM(p_combustible),
           PRECIO = p_precio,
           COLOR = TRIM(p_color),
           DESCRIPCION = p_descripcion
     WHERE ID_VEHICULO = p_id;

    IF SQL%ROWCOUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20021, 'Vehículo no existe');
    END IF;
  END;

  PROCEDURE SP_INACTIVAR(p_id IN NUMBER) IS
  BEGIN
    UPDATE VEHICULOS
       SET ESTADO_VEHICULO = 'INACTIVO'
     WHERE ID_VEHICULO = p_id;

    IF SQL%ROWCOUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20022, 'Vehículo no existe');
    END IF;
  END;

END PKG_VEHICULOS;
/

PROMPT === 2) (Opcional recomendado) PKG_USUARIOS para Login (sin SQL en Python) ===

CREATE OR REPLACE PACKAGE PKG_USUARIOS AS
  PROCEDURE SP_VALIDAR_LOGIN(
    p_correo      IN VARCHAR2,
    p_password    IN VARCHAR2,
    p_ok          OUT NUMBER,
    p_id_usuario  OUT NUMBER,
    p_id_rol      OUT NUMBER
  );
END PKG_USUARIOS;
/

CREATE OR REPLACE PACKAGE BODY PKG_USUARIOS AS

  PROCEDURE SP_VALIDAR_LOGIN(
    p_correo      IN VARCHAR2,
    p_password    IN VARCHAR2,
    p_ok          OUT NUMBER,
    p_id_usuario  OUT NUMBER,
    p_id_rol      OUT NUMBER
  ) IS
  BEGIN
    p_ok := 0;
    p_id_usuario := NULL;
    p_id_rol := NULL;

    SELECT ID_USUARIO, ID_ROL
      INTO p_id_usuario, p_id_rol
      FROM USUARIOS
     WHERE CORREO = TRIM(LOWER(p_correo))
       AND CONTRASENA_ENCRIPTADA = p_password
       AND ESTADO_CUENTA = 'ACTIVO';

    p_ok := 1;

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      p_ok := 0;
      p_id_usuario := NULL;
      p_id_rol := NULL;
  END SP_VALIDAR_LOGIN;

END PKG_USUARIOS;
/

SELECT object_name, object_type, status
FROM user_objects
WHERE object_name IN ('PKG_USUARIOS','PKG_VEHICULOS');

